# Generated by Django 5.1.4 on 2025-01-12 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('apelido', models.CharField(blank=True, max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=50)),
                ('matricula', models.CharField(blank=True, max_length=254, unique=True)),
                ('nivel', models.CharField(choices=[('A', 'Administrador'), ('B', 'Bibliotecário'), ('C', 'Coordenador'), ('D', 'Diretor'), ('P', 'Professor'), ('O', 'Aluno'), ('T', 'TI'), ('S', 'Secretária'), ('V', 'Visitante')], default='V', max_length=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('login', models.BooleanField(default=False)),
                ('ferias', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
