# Generated by Django 5.1.4 on 2025-01-12 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_initial'),
        ('tabela', '0002_remove_turma_materia_materia_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colaboradores', to='tabela.turma'),
        ),
    ]
