# Generated by Django 5.1.4 on 2025-01-12 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_colaborador_turma'),
        ('tabela', '0003_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='colaboradores', to='tabela.matricula'),
        ),
    ]
