# Generated by Django 5.1.4 on 2025-02-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_remove_colaborador_cargo_remove_colaborador_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='descricao',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
