# Generated by Django 5.1.4 on 2025-01-12 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Competência',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Ensino',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
                ('horario_inicio', models.TimeField(db_index=True)),
                ('horario_fim', models.TimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Ensino',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Período',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
                ('horario', models.TimeField(db_index=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='materias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matéria',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='tabela.materia')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('AV1', 'Avaliação 1'), ('AV2', 'Avaliação 2'), ('AV3', 'Avaliação 3'), ('FINAL', 'Prova Final'), ('REC', 'Recuperação')], default='AV1', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tabela.materia')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turmas', to='tabela.competencia')),
                ('ensino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turmas', to='tabela.ensino')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turmas', to='tabela.materia')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turmas', to='tabela.periodo')),
            ],
            options={
                'verbose_name': 'Turma',
            },
        ),
    ]
