# Generated by Django 5.1.4 on 2025-01-12 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='materia',
        ),
        migrations.AddField(
            model_name='materia',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turmas', to='tabela.turma'),
        ),
    ]
