# Generated by Django 5.1.4 on 2025-01-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0005_alter_matriculaturma_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaturma',
            name='status',
            field=models.CharField(choices=[('M', 'Matriculado'), ('T', 'Transferido'), ('A', 'Aprovado'), ('R', 'Reprovado')], default='M', max_length=1),
        ),
    ]
