# Generated by Django 5.1.4 on 2025-01-12 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0006_alter_matriculaturma_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='aluno',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='matricula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='tabela.matriculaturma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tabela.matriculaturma'),
            preserve_default=False,
        ),
    ]
