# Generated by Django 5.1.4 on 2025-01-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0007_remove_frequencia_aluno_remove_nota_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='materias', to='tabela.turma'),
        ),
    ]
