# Generated by Django 5.1.4 on 2025-01-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0008_alter_materia_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='cor',
            field=models.CharField(default='#2490CA', max_length=7),
        ),
    ]
