# Generated by Django 5.1.4 on 2025-01-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0009_frequencia_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='cor',
        ),
        migrations.AddField(
            model_name='materia',
            name='cor',
            field=models.CharField(default='#67E95F', max_length=7),
        ),
    ]
