# Generated by Django 5.1.4 on 2025-01-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0010_remove_frequencia_cor_materia_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='cor',
            field=models.CharField(default='#293601', max_length=7),
        ),
    ]
