# Generated by Django 5.1.4 on 2025-01-16 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0011_alter_materia_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadroHorario',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='materia',
            name='cor',
            field=models.CharField(default='#51B16D', max_length=7),
        ),
        migrations.AddField(
            model_name='matriculaturma',
            name='quadro_horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='tabela.quadrohorario'),
            preserve_default=False,
        ),
    ]
