# Generated by Django 5.1.4 on 2025-01-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0012_quadrohorario_alter_materia_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='cor',
            field=models.CharField(default='#54A80C', max_length=7),
        ),
    ]
