# Generated by Django 5.1.4 on 2025-01-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_remove_colaborador_cargo_remove_colaborador_turma'),
        ('tabela', '0013_alter_materia_cor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ensino',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='matriculaturma',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='matriculaturma',
            name='quadro_horario',
        ),
        migrations.RemoveField(
            model_name='matriculaturma',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='periodo',
        ),
        migrations.DeleteModel(
            name='Competencia',
        ),
        migrations.DeleteModel(
            name='Ensino',
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='QuadroHorario',
        ),
        migrations.DeleteModel(
            name='MatriculaTurma',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
