# Generated by Django 5.1.4 on 2025-02-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0014_delete_cargo_remove_turma_competencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
