# Generated by Django 5.1.4 on 2025-01-16 03:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Landing Page',
            },
        ),
    ]
