# Generated by Django 5.1.4 on 2025-02-15 19:26

import apps.landingpage.models
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.landingpage.models.programas_upload_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.landingpage.models.programas_upload_path, verbose_name='Imagem')),
                ('evento', models.DateField(blank=True, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário Início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário Fim')),
                ('localizacao', models.CharField(blank=True, max_length=254, null=True, verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Oferecemos',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.landingpage.models.programas_upload_path, verbose_name='Imagem')),
                ('descricao_1', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Oferecemos',
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=254, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.landingpage.models.programas_upload_path, verbose_name='Imagem')),
                ('descricao_1', models.CharField(blank=True, max_length=254, null=True)),
                ('descricao_2', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Programas',
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='aniversario',
            field=models.DateField(blank=True, null=True, verbose_name='Aniversário'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ano',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cep',
            field=models.CharField(blank=True, max_length=12, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='contato',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='descricao',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='facebook',
            field=models.CharField(blank=True, max_length=354, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='funcionamento_dom',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='funcionamento_qua',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='funcionamento_qui',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='funcionamento_sab',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='funcionamento_seg',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='funcionamento_sex',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='funcionamento_ter',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.landingpage.models.eas_upload_path, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='instagram',
            field=models.CharField(blank=True, max_length=354, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='linkedin',
            field=models.CharField(blank=True, max_length=354, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='missao_valor_complemento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='missao_valor_item_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='missao_valor_item_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='missao_valor_item_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='missao_valor_item_4',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='missao_valor_item_5',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='missao_valor_item_6',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='missao_valor_titulo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='principal_texto',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='uf',
            field=models.CharField(default='PE', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='x',
            field=models.CharField(blank=True, max_length=354, null=True),
        ),
    ]
