# Generated by Django 5.1.4 on 2025-02-15 20:14

import apps.landingpage.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_colaboradores_eventos_oferecemos_programas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.landingpage.models.colaboradores_upload_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.landingpage.models.eventos_upload_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='oferecemos',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=apps.landingpage.models.oferecemos_upload_path, verbose_name='Imagem'),
        ),
    ]
