# Generated by Django 5.1.4 on 2025-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_colaboradores_image_alter_eventos_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
